### ISSUE TITLE
Issue with mysql Timestamp column 

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/DataflowTemplates#191] opened 2020-11-11 18:59 UTC
I am using JDBC to Bigquery dataflow template. Getting below error with mysql Timestamp column.

` "Cannot return an invalid timestamp value of 1605052806000000000 microseconds relative to the Unix epoch. The range of valid timestamp values is [0001-01-1 00:00:00, 9999-12-31 23:59:59.999999]; error in writing field mod_timestamp", "reason" : "invalidQuery" }`

Why Timestamp column is not being migrated to bigquery properly? Shall i use different datatype in mysql instead of using Timestamp?

Attached screenshots for more information of my Mysql table (name = mysql3) :
![image](https://user-images.githubusercontent.com/66572191/98851024-a9022700-247b-11eb-9a10-4c9001953a35.png)
![image](https://user-images.githubusercontent.com/66572191/98851063-b7e8d980-247b-11eb-8964-6328277afdbe.png)

**Comment by damienhollis** [comment] 2020-11-12 22:04
My PR https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/192 might address this issue - although I'm not 100% sure what the problem is.

**Comment by ayush-poddar** [comment] 2021-06-23 02:24
This issue should be fixed by PR #253, this error seems to be thrown by BigQuery when loading data from GCS which has timestamp in milliseconds / microseconds as it only expects seconds. 
I believe that having it in milliseconds / microseconds in general crosses the valid timestamp range when expectation is in seconds.

**Comment by bvolpato** [comment] 2023-02-06 04:28
Fixed by https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/253.

--

This issue has been stale for some time now. Please reopen it if there is a follow up or any related questions.

**Closed by bvolpato** 2023-02-06 04:28 UTC
