### ISSUE TITLE
[Feature Request]: include Pub/Sub message by default

### ISSUE THREAD

**Issue by florentinchaussoy** [GoogleCloudPlatform/DataflowTemplates#1155] opened 2023-11-10 10:47 UTC
### Related Template(s)

Pub/Sub to Datadog template

### What feature(s) are you requesting?

Hello,

Datadog has changed its [recommendations](https://docs.datadoghq.com/integrations/google_cloud_platform/#log-collection) regarding the way to forward logs from Google Cloud Platform. The previous implementation, [collecting Google Cloud logs with a Pub/Sub Push subscription](https://docs.datadoghq.com/logs/guide/collect-google-cloud-logs-with-push/), is going to be deprecated.

In order to ensure a migration as smooth as possible with your dear users, I strongly recommend to switch the [current boolean](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/0769d5bcd9aad6c3023610eede6ef24f79940aae/v1/src/main/java/com/google/cloud/teleport/templates/PubSubToDatadog.java#L142) 'includePubsubMessage' to true. Both reasons:

1. That's simply how the Google Cloud integrations (e.g. Cloud Run) maintained by Datadog are currently working;
2. To avoid any breaking changes in the current implementations.

Thank you for taking into consideration my feature request.

Florentin

**Comment by florentinchaussoy** [comment] 2023-11-10 11:17
Here is the related pull request if all is good in your side: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1156.

**Comment by ash-ddog** [comment] 2023-11-28 22:41
👋 Hey @florentinchaussoy, thanks for raising and for the PR. 🙏 

While I understand that the previous, deprecated procedure of using a Google Cloud Pub/Sub Push subscription includes in the HTTP POST the Pub/Sub message metadata (such as `message_id` and `publish_time`), I do not think we should include the Pub/Sub message metadata by default.

With either solution (i.e. Pub/Sub Push or the PubSubToDatadog Dataflow template), the goal is to forward logs from Google Cloud to Datadog. The Pub/Sub message metadata is extraneous and irrelevant in terms of that goal. Additionally, the metadata isn't even related to the log event in anyway; it's just an envelope for the data.

I'm guessing here, but I think most Datadog clients have no need to receive the Pub/Sub message metadata and only care about the log event. So turning this option on by default would mean extra bytes to send over the wire when the majority of the time, that data will be thrown away. TBH, the Datadog docs for the original procedure probably should have instructed users to use [payload unwrapping](https://cloud.google.com/pubsub/docs/payload-unwrapping) to not include the message metadata.

And of course, if you need the metadata for some reason, the option is there! Is there any reason the option doesn't suffice for your use case? If documentation is the problem, I'd be happy to work to get a note added about the change in behavior and mention the option explicitly. 🙏

**Comment by ash-ddog** [comment] 2023-12-27 15:27
👋 Providing an update here. Datadog recently identified issues with our OOTB log processors for our Google Cloud integrations which were caused by the switch to the Dataflow solution for log collection (due to the fact that log messages stopped being wrapped in a root `data` attribute). These issues have since been fixed.

Going to close this issue due to the fixes and staleness. 🙏

**Closed by ash-ddog** 2023-12-27 15:27 UTC
Labels: addition, p2, needs triage
